name: smart_pay_by_apex
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  get_storage: ^2.1.1
  go_navigator: ^1.0.0
  google_fonts: ^6.2.0
  pin_code_text_field: ^1.8.0
  webview_flutter: ^4.5.0
  intl: ^0.19.0
  loading_progress_indicator: ^0.1.6
  in_app_notification: ^1.1.2
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true


  assets:
    - assets/images/jpg/
    - assets/images/png/
    - assets/images/svg/

    - assets/icons/jpg/
    - assets/icons/svg/
    - assets/icons/png/

    - assets/fonts/


