name: smart_pay_by_apex
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  go_navigator: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true


  assets:
    - assets/images/jpg/
    - assets/images/png/
    - assets/images/svg/

    - assets/icons/jpg/
    - assets/icons/svg/
    - assets/icons/png/

    - assets/fonts/


